apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: sketc-local-mysql1
  labels:
    app: mysql
data:
  primary.cnf: |
    # 主节点应用这个配置
    [mysqld]
    log-bin
    default_authentication_plugin= mysql_native_password
  replica.cnf: |
    # 从节点应用这个配置
    [mysqld]
    super-read-only
    default_authentication_plugin= mysql_native_password