apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: sketc-local-mysql1
type: Opaque
data:
  password: UGFzc3dvcmQkMTIzNDU2 # Password$123456
  admin-password: UGFzc3dvcmQkMTIzNDU2 # Password$123456