apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: headles-svc-test
    qcloud-app: headles-svc-test
  name: headles-svc-test
  namespace: sketc-local-mysql1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: headles-svc-test
      qcloud-app: headles-svc-test
  serviceName: headles-svc-test
  template:
    metadata:
      labels:
        k8s-app: headles-svc-test
        qcloud-app: headles-svc-test
    spec:
      containers:
      - image: nginx:latest
        # imagePullPolicy: Always
        name: headles-svc-test
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations: 
          volume.beta.kubernetes.io/storage-class: nfs # 对应第2步创建的 StorageClass 的名称
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: "nfs" 不能这样写，需要在 annotations 字段传入，原因未知
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: headles-svc-test
    qcloud-app: headles-svc-test
  name: headles-svc-test
  namespace: sketc-local-mysql1
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: 80-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: headles-svc-test
    qcloud-app: headles-svc-test
  sessionAffinity: None
  type: ClusterIP